"""add_case_shares

Revision ID: 05bffdaca56b
Revises: 59c3d8d0fbcf
Create Date: 2026-05-13 22:17:08.415759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bffdaca56b'
down_revision: Union[str, Sequence[str], None] = '59c3d8d0fbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'shared_with_id', name='uq_case_share')
    )
    op.create_index(op.f('ix_case_shares_case_id'), 'case_shares', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_shares_id'), 'case_shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_shares_id'), table_name='case_shares')
    op.drop_index(op.f('ix_case_shares_case_id'), table_name='case_shares')
    op.drop_table('case_shares')
    # ### end Alembic commands ###
